spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8088}"
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1